name: 🚀 Feature request
description: Request a change that is not a bug fix
title: "[Feature] <title>"
labels: ["type/feature", triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature for this?
      description: Please search to see if an issue already exists for the feature you request.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
