name: ci-cd

on:
  push:
    tags:
      - v*

env:
  artifactName: sharepoint-package
  artifactPath: sharepoint/solution
  sharepointPackageName: trust-365
  node-version: 16
  pnpm-version: 8

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PNPM ${{ env.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.pnpm-version }}

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test
        run: gulp test

      - name: Ship SharePoint package
        run: |
          gulp bundle --ship
          gulp package-solution --ship

      - name: Archive SharePoint Package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifactName }}
          path: ${{ env.artifactPath }}
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download SharePoint Package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.artifactName }}

      - name: Login to tenant
        uses: pnp/action-cli-login@v2.2.1
        with:
          APP_ID: ${{ secrets.APP_ID }}
          TENANT: ${{ secrets.TENANT_ID }}
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

      - name: Deploy to tenant
        uses: pnp/action-cli-deploy@v3.0.1
        with:
          APP_FILE_PATH: ${{ env.sharepointPackageName }}.sppkg
          SKIP_FEATURE_DEPLOYMENT: true
          OVERWRITE: true

