name: ci-cd

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    needs: [setup]
    steps:
      - run: pnpm test
