name: ci-cd
run-name: Running CI/CD
on: [push]
env:
  sppkgPath: sharepoint/solution/trust-365.sppkg
  node-version: 16
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'pnpm'
      - name: Install deps, test, build and package
        run: |
          pnpm install
          gulp test
          gulp bundle --ship
          gulp package-solution --ship
      - name: Upload sppkg
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: ${{ env.sppkgPath }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download sppkg
        uses: actions/download-artifact@v3

      - name: Login to tenant
        uses: pnp/action-cli-login@v2.2.1
        with:
          APP_ID: ${{ secrets.APP_ID }}
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          # CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Status
        uses: pnp/action-cli-runscript@v2.0.1
        with:
          CLI_MICROSOFT365_SCRIPT : m365 status
          #M365_CLI_SCRIPT: m365 status


      # - name: Deploy to tenant
      #   uses: pnp/action-cli-deploy@v3.0.1
      #   with:
      #     APP_FILE_PATH: package/trust-365.sppkg
      #     SKIP_FEATURE_DEPLOYMENT: true
      #     OVERWRITE: true

